// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by AffineScript compiler (Deno-ESM target, issue #122)
// ---- AffineScript Deno-ESM runtime ----
const Some = (value) => ({ tag: "Some", value });
const None = { tag: "None" };
const Ok   = (value) => ({ tag: "Ok",  value });
const Err  = (error) => ({ tag: "Err", error });
const Unit = null;
const print   = (s) => { Deno.stdout.writeSync(new TextEncoder().encode(String(s))); };
const println = (s) => { console.log(String(s)); };
// ---- Deno host shims (extern fn lowering targets, issue #122) ----
// Kept tiny + inlined so emitted modules are genuinely drop-in (no extra
// package to publish or resolve). The same surface is mirrored, for
// standalone `deno test`, by packages/affine-deno/mod.js.
const __as_ensureDir = (p) => {
  try { Deno.mkdirSync(p, { recursive: true }); }
  catch (e) { if (!(e instanceof Deno.errors.AlreadyExists)) throw e; }
};
const __as_pathJoin = (a, b) => {
  if (a.length === 0) return b;
  const sep = a.endsWith("/") || a.endsWith("\\") ? "" : "/";
  return a + sep + b;
};
const __as_readDirNames = (p) => {
  const names = [];
  for (const entry of Deno.readDirSync(p)) {
    if (entry.isFile) names.push(entry.name);
  }
  return names;
};
const __as_isNotFound = (e) => (e instanceof Deno.errors.NotFound);
const __as_walkRecursive = (root) => {
  const out = [];
  const rec = (dir) => {
    for (const entry of Deno.readDirSync(dir)) {
      const full = (dir.endsWith("/") ? dir : dir + "/") + entry.name;
      if (entry.isFile) out.push(full);
      else if (entry.isDirectory) rec(full);
    }
  };
  rec(root);
  return out;
};
const __as_regexMatch = (s, pat) => new RegExp(pat).test(String(s));
const __as_wasmInstance = (bytes) =>
  new WebAssembly.Instance(new WebAssembly.Module(bytes)).exports;
const __as_wasmCall = (exports, name, args) => Number(exports[name](...(args || [])));
// ---- motion (bindings #4): consumer-provided import ----
// Host JS environment must expose globalThis.__as_motion (the motion
// library or a compatible mock). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import * as m from "motion"; globalThis.__as_motion = m;` once at
// module-init time. The AffineScript-side externs (stdlib/Motion.affine)
// don't see this indirection — they call __as_motion* helpers directly.
const __as_motionAnimate = (target, keyframes, options) =>
  globalThis.__as_motion.animate(target, keyframes, options);
const __as_motionAwait = (controls) =>
  Promise.resolve(controls).then(() => 0);
const __as_motionCancel = (controls) => {
  if (controls && typeof controls.cancel === "function") controls.cancel();
  return 0;
};
// `animateMini` / `tween` / `spring` / `ease` — bindings #4 follow-up
// surface. Each helper resolves the host method on globalThis.__as_motion
// at call time so a mock that only stubs a subset still works for the
// rest (the smoke harness exercises every variant).
const __as_motionAnimateMini = (target, keyframes, options) =>
  globalThis.__as_motion.animateMini(target, keyframes, options);
const __as_motionTween = (target, from, to, options) =>
  globalThis.__as_motion.tween(target, from, to, options);
const __as_motionSpring = (target, keyframes, springConfig) =>
  globalThis.__as_motion.spring(target, keyframes, springConfig);
const __as_motionEase = (name) =>
  globalThis.__as_motion.ease(name);
// ---- pixi.js (bindings #1): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi (the PIXI namespace
// from `import * as PIXI from "pixi.js"`). Tests set it in the harness
// before importing the generated module.
const __as_pixiAppInit = async (options) => {
  const app = new globalThis.__as_pixi.Application();
  await app.init(options);
  return app;
};
const __as_pixiAppCanvas = (app) => app.canvas;
const __as_pixiAppStage = (app) => app.stage;
const __as_pixiAppTicker = (app) => app.ticker;
const __as_pixiAppDestroy = (app) => { app.destroy(); return 0; };
const __as_pixiContainerNew = () => new globalThis.__as_pixi.Container();
const __as_pixiContainerAddChild = (p, c) => { p.addChild(c); return 0; };
const __as_pixiContainerRemoveChild = (p, c) => { p.removeChild(c); return 0; };
const __as_pixiContainerSetPosition = (c, x, y) => { c.x = x; c.y = y; return 0; };
const __as_pixiContainerSetVisible = (c, v) => { c.visible = v; return 0; };
const __as_pixiContainerDestroy = (c) => { c.destroy(); return 0; };
const __as_pixiSpriteFrom = (t) => new globalThis.__as_pixi.Sprite(t);
// Upcasts are identity — PIXI's class hierarchy makes Sprite/Graphics/
// Text actual Container subclasses, so the JS object is the same.
const __as_pixiSpriteAsContainer = (s) => s;
const __as_pixiTextureFromUrl = (url) => globalThis.__as_pixi.Texture.from(url);
const __as_pixiGraphicsNew = () => new globalThis.__as_pixi.Graphics();
const __as_pixiGraphicsRect = (g, x, y, w, h) => { g.rect(x, y, w, h); return 0; };
const __as_pixiGraphicsFill = (g, color) => { g.fill({ color }); return 0; };
const __as_pixiGraphicsClear = (g) => { g.clear(); return 0; };
const __as_pixiGraphicsAsContainer = (g) => g;
const __as_pixiTextNew = (options) => new globalThis.__as_pixi.Text(options);
const __as_pixiTextSetText = (t, content) => { t.text = content; return 0; };
const __as_pixiTextAsContainer = (t) => t;
const __as_pixiTickerAdd = (t, cb) => { t.add(cb); return 0; };
const __as_pixiTickerStart = (t) => { t.start(); return 0; };
const __as_pixiTickerStop = (t) => { t.stop(); return 0; };
// ---- @pixi/ui (bindings #3): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_ui (the namespace
// from `import * as PixiUI from "@pixi/ui"`). Tests set it in the
// harness before importing the generated module; production
// consumers typically do once at module-init time. The
// AffineScript-side externs (stdlib/PixiUI.affine) don't see this
// indirection — they call __as_pixiUi* helpers directly.
//
// Upcasts to Container are identity — @pixi/ui's Button /
// FancyButton / Slider / Switch are all real PIXI.Container
// subclasses, so the JS object is the same.
const __as_pixiUiButtonNew         = (options) => new globalThis.__as_pixi_ui.Button(options);
const __as_pixiUiButtonOnPress     = (b, cb)   => { b.onPress.connect(cb); return 0; };
const __as_pixiUiButtonAsContainer = (b)       => b;
const __as_pixiUiFancyButtonNew         = (options) => new globalThis.__as_pixi_ui.FancyButton(options);
const __as_pixiUiFancyButtonAsContainer = (b)       => b;
const __as_pixiUiSliderNew         = (options) => new globalThis.__as_pixi_ui.Slider(options);
const __as_pixiUiSliderOnUpdate    = (s, cb)   => { s.onUpdate.connect(cb); return 0; };
const __as_pixiUiSliderAsContainer = (s)       => s;
const __as_pixiUiSwitchNew         = (options) => new globalThis.__as_pixi_ui.Switch(options);
const __as_pixiUiSwitchOnChange    = (sw, cb)  => { sw.onChange.connect(cb); return 0; };
const __as_pixiUiSwitchAsContainer = (sw)      => sw;
// ---- @pixi/sound (bindings #2): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_sound (the `Sound`
// named export from `@pixi/sound`). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import { Sound } from "@pixi/sound"; globalThis.__as_pixi_sound = Sound;`
// once at module-init time. The AffineScript-side externs
// (stdlib/PixiSound.affine) don't see this indirection — they call
// __as_pixiSound* helpers directly.
const __as_pixiSoundFrom = (url) => globalThis.__as_pixi_sound.from(url);
const __as_pixiSoundPlay = (s) => { s.play(); return 0; };
const __as_pixiSoundStop = (s) => { s.stop(); return 0; };
const __as_pixiSoundPause = (s) => { s.pause(); return 0; };
const __as_pixiSoundResume = (s) => { s.resume(); return 0; };
const __as_pixiSoundSetVolume = (s, vol) => { s.volume = vol; return 0; };
const __as_pixiSoundSetLoop = (s, loop) => { s.loop = loop; return 0; };
// `++` is overloaded (string concat / array concat); `a + b` would
// stringify arrays. Dispatch on shape so stdlib/string.affine's
// `result ++ [x]` and `a ++ b` are both correct.
const __as_concat = (a, b) => Array.isArray(a) ? a.concat(b) : (a + b);
// Honest host/runtime primitives underpinning the AffineScript-level
// stdlib/string.affine (its is_empty/starts_with/ends_with/split/join/
// replace/... are real AffineScript on top of these).
const __as_strSub = (s, start, n) => String(s).slice(start, start + n);
const __as_strGet = (s, i) => String(s)[i];
const __as_strFind = (s, n) => String(s).indexOf(n);
const __as_charToInt = (c) => String(c).codePointAt(0);
const __as_intToChar = (n) => String.fromCodePoint(n);
const __as_parseInt = (s) => {
  const n = parseInt(String(s), 10);
  return Number.isNaN(n) ? None : Some(n);
};
const __as_parseFloat = (s) => {
  const n = parseFloat(String(s));
  return Number.isNaN(n) ? None : Some(n);
};
const __as_show = (v) => (typeof v === "string" ? v : JSON.stringify(v));
// ---- Http (issue #160): portable fetch round-trip ----
// `headers` crosses the boundary as an AffineScript [(String, String)]
// assoc list == JS array of [name, value] pairs. `body` is an
// AffineScript Option<String> == { tag: "Some", value } | { tag: "None" }.
// The result is the `Response` record shape { status, headers, body }.
const __as_httpHeadersToObject = (pairs) => {
  const o = {};
  for (const kv of (pairs || [])) o[kv[0]] = kv[1];
  return o;
};
const __as_httpHeadersFromResponse = (res) => {
  const out = [];
  res.headers.forEach((value, key) => out.push([key, value]));
  return out;
};
// ---- hpm-json-rsr Zig FFI shims (stdlib/json.affine v0.3) ----
// `HpmJsonValue` is opaque to AffineScript; on Deno-ESM it's just the
// underlying JS value from JSON.parse. The shims mirror the sentinel
// conventions of the Zig exports so the AffineScript-side wrappers
// (`to_json`, `parse`) behave identically across backends.
const __as_hpmJsonParse = (s) => {
  try { return Some(JSON.parse(String(s))); } catch (_e) { return None; }
};
const __as_hpmJsonFree = (_v) => 0;
const __as_hpmJsonType = (v) => {
  if (v === null || v === undefined) return 0;
  if (typeof v === "boolean") return 1;
  if (typeof v === "number")  return Number.isInteger(v) ? 2 : 3;
  if (typeof v === "string")  return 4;
  if (Array.isArray(v))       return 5;
  if (typeof v === "object")  return 6;
  return -1;
};
const __as_hpmJsonBool = (v) => (typeof v === "boolean" ? (v ? 1 : 0) : -1);
const __as_hpmJsonInt = (v) =>
  (typeof v === "number" ? Math.trunc(v) : Number.MIN_SAFE_INTEGER);
const __as_hpmJsonFloat = (v) => (typeof v === "number" ? v : NaN);
const __as_hpmJsonString = (v) => (typeof v === "string" ? v : "");
const __as_hpmJsonObjectGet = (v, k) => {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return None;
  return Object.prototype.hasOwnProperty.call(v, String(k))
    ? Some(v[String(k)]) : None;
};
const __as_hpmJsonArrayLen = (v) => (Array.isArray(v) ? v.length : 0);
const __as_hpmJsonArrayGet = (v, i) => {
  if (!Array.isArray(v)) return None;
  const idx = Number(i);
  return (idx >= 0 && idx < v.length) ? Some(v[idx]) : None;
};
const __as_hpmJsonEscapeString = (s) => {
  let out = "";
  const src = String(s);
  for (let i = 0; i < src.length; i++) {
    const c = src.charCodeAt(i);
    if (c === 0x22) out += "\\\"";
    else if (c === 0x5c) out += "\\\\";
    else if (c === 0x0a) out += "\\n";
    else if (c === 0x0d) out += "\\r";
    else if (c === 0x09) out += "\\t";
    else if (c === 0x08) out += "\\b";
    else if (c === 0x0c) out += "\\f";
    else if (c < 0x20) out += "\\u00" + c.toString(16).padStart(2, "0");
    else out += src[i];
  }
  return out;
};
const __as_httpFetch = async (url, method, headers, bodyOpt) => {
  const init = { method, headers: __as_httpHeadersToObject(headers) };
  if (bodyOpt && bodyOpt.tag === "Some") init.body = bodyOpt.value;
  // `globalThis.fetch` explicitly: the stdlib `Http.fetch` compiles to a
  // module-level `function fetch`, which would otherwise shadow the host.
  const res = await globalThis.fetch(url, init);
  const text = await res.text();
  return {
    status: res.status,
    headers: __as_httpHeadersFromResponse(res),
    body: text,
  };
};
// ---- end runtime ----

function sensoryLevelDescription(level) {
  if ((level <= 2)) { return "Very Low";  }
  if ((level <= 4)) { return "Low";  }
  if ((level <= 6)) { return "Moderate";  }
  if ((level <= 8)) { return "High";  }
  return "Very High";
}

function isValidSensoryLevel(level) {
  return ((level >= 0) && (level <= 10));
}

// type SensoryProfile
function validateSensoryProfile(p) {
  return ((isValidSensoryLevel(p.noise) && isValidSensoryLevel(p.light)) && isValidSensoryLevel(p.crowd));
}

function exceedsProfile(levels, profile) {
  return (((levels.noise > profile.noise) || (levels.light > profile.light)) || (levels.crowd > profile.crowd));
}

function assert_eq_str(actual, expected, message) {
  if ((actual !== expected)) { const _id0 = (console.error(__as_concat(__as_concat(__as_concat(__as_concat(__as_concat(__as_concat("FAIL: ", message), " \u2014 expected '"), expected), "', got '"), actual), "'")), 0); return Deno.exit(1);  }
  return 0;
}

function assert_true(condition, message) {
  if ((!condition)) { const _id1 = (console.error(__as_concat("FAIL: ", message)), 0); return Deno.exit(1);  }
  return 0;
}

function assert_false(condition, message) {
  if (condition) { const _id2 = (console.error(__as_concat("FAIL (expected false): ", message)), 0); return Deno.exit(1);  }
  return 0;
}

function test_sensory_very_low() {
  const _id3 = assert_eq_str(sensoryLevelDescription(0), "Very Low", "sensoryLevelDescription: 0 -> Very Low");
  const _id4 = assert_eq_str(sensoryLevelDescription(1), "Very Low", "sensoryLevelDescription: 1 -> Very Low");
  const _id5 = assert_eq_str(sensoryLevelDescription(2), "Very Low", "sensoryLevelDescription: 2 -> Very Low");
  return 0;
}

function test_sensory_low() {
  const _id6 = assert_eq_str(sensoryLevelDescription(3), "Low", "sensoryLevelDescription: 3 -> Low");
  const _id7 = assert_eq_str(sensoryLevelDescription(4), "Low", "sensoryLevelDescription: 4 -> Low");
  return 0;
}

function test_sensory_moderate() {
  const _id8 = assert_eq_str(sensoryLevelDescription(5), "Moderate", "sensoryLevelDescription: 5 -> Moderate");
  const _id9 = assert_eq_str(sensoryLevelDescription(6), "Moderate", "sensoryLevelDescription: 6 -> Moderate");
  return 0;
}

function test_sensory_high() {
  const _id10 = assert_eq_str(sensoryLevelDescription(7), "High", "sensoryLevelDescription: 7 -> High");
  const _id11 = assert_eq_str(sensoryLevelDescription(8), "High", "sensoryLevelDescription: 8 -> High");
  return 0;
}

function test_sensory_very_high() {
  const _id12 = assert_eq_str(sensoryLevelDescription(9), "Very High", "sensoryLevelDescription: 9 -> Very High");
  const _id13 = assert_eq_str(sensoryLevelDescription(10), "Very High", "sensoryLevelDescription: 10 -> Very High");
  return 0;
}

function test_valid_level_accepts() {
  const _id14 = assert_true(isValidSensoryLevel(0), "isValidSensoryLevel accepts 0");
  const _id15 = assert_true(isValidSensoryLevel(5), "isValidSensoryLevel accepts 5");
  const _id16 = assert_true(isValidSensoryLevel(10), "isValidSensoryLevel accepts 10");
  return 0;
}

function test_valid_level_rejects_negative() {
  const _id17 = assert_false(isValidSensoryLevel((0 - 1)), "isValidSensoryLevel rejects -1");
  return 0;
}

function test_valid_level_rejects_above_10() {
  const _id18 = assert_false(isValidSensoryLevel(11), "isValidSensoryLevel rejects 11");
  return 0;
}

function test_validate_accepts_valid() {
  const p = ({ noise: 5, light: 6, crowd: 4 });
  const _id19 = assert_true(validateSensoryProfile(p), "validateSensoryProfile accepts {5,6,4}");
  return 0;
}

function test_validate_rejects_invalid_noise() {
  const p = ({ noise: 11, light: 5, crowd: 5 });
  const _id20 = assert_false(validateSensoryProfile(p), "validateSensoryProfile rejects noise=11");
  return 0;
}

function test_validate_rejects_negative_light() {
  const p = ({ noise: 5, light: (0 - 1), crowd: 5 });
  const _id21 = assert_false(validateSensoryProfile(p), "validateSensoryProfile rejects light=-1");
  return 0;
}

function test_exceeds_returns_true_when_exceeded() {
  const levels = ({ noise: 7, light: 6, crowd: 5 });
  const profile = ({ noise: 6, light: 5, crowd: 5 });
  const _id22 = assert_true(exceedsProfile(levels, profile), "exceedsProfile: levels exceed");
  return 0;
}

function test_exceeds_returns_false_when_within() {
  const levels = ({ noise: 5, light: 4, crowd: 3 });
  const profile = ({ noise: 6, light: 5, crowd: 5 });
  const _id23 = assert_false(exceedsProfile(levels, profile), "exceedsProfile: levels within");
  return 0;
}

function test_exceeds_returns_false_when_equal() {
  const levels = ({ noise: 5, light: 5, crowd: 5 });
  const profile = ({ noise: 5, light: 5, crowd: 5 });
  const _id24 = assert_false(exceedsProfile(levels, profile), "exceedsProfile: levels equal profile");
  return 0;
}

function test_exceeds_returns_true_when_any_exceeds() {
  const levels = ({ noise: 4, light: 4, crowd: 6 });
  const profile = ({ noise: 5, light: 5, crowd: 5 });
  const _id25 = assert_true(exceedsProfile(levels, profile), "exceedsProfile: crowd exceeds");
  return 0;
}

export function main() {
  const _id26 = test_sensory_very_low();
  const _id27 = test_sensory_low();
  const _id28 = test_sensory_moderate();
  const _id29 = test_sensory_high();
  const _id30 = test_sensory_very_high();
  const _id31 = test_valid_level_accepts();
  const _id32 = test_valid_level_rejects_negative();
  const _id33 = test_valid_level_rejects_above_10();
  const _id34 = test_validate_accepts_valid();
  const _id35 = test_validate_rejects_invalid_noise();
  const _id36 = test_validate_rejects_negative_light();
  const _id37 = test_exceeds_returns_true_when_exceeded();
  const _id38 = test_exceeds_returns_false_when_within();
  const _id39 = test_exceeds_returns_false_when_equal();
  const _id40 = test_exceeds_returns_true_when_any_exceeds();
  println("OK: 15 helper tests passed");
  return 0;
}

await main();
